spring.application.name=webservices
logging.level.org.springframework.ws=TRACE
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.oxm=DEBUG
logging.level.org.springframework.web=DEBUG
security.api-key=my-secret-key